---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    tekton.dev/tags: rpm-build
  name: pre-build-script
spec:
  description: |
    Takes a source artifact, extracts it, and runs a custom script
    to modify the contents (e.g., generate a spec file, download sources).
    It then outputs a new, manipulated source artifact.
  params:
  - name: source-artifact
    description: The Trusted Artifact URI from the clone-repository task.
    type: string
  - name: ociStorage
    description: The OCI repository where the new Trusted Artifact will be stored.
    type: string
  - name: ociArtifactExpiresAfter
    description: How long the new Trusted Artifact should be retained.
    type: string
  - name: script-environment-image
    description: OCI image with tools (skopeo, jq, etc.) needed by the custom script.
    type: string
  - name: script-content
    description: The bash script to execute on the source files.
    type: string
  - name: context
    description: The sub-directory within the source to run the script from.
    type: string
    default: "."
  results:
  - name: manipulated-source-artifact
    description: The Trusted Artifact URI pointing to the modified source.
    type: string
  workspaces:
  - name: workdir
    description: A workspace for all the operations.
  steps:
  - name: use-trusted-artifact
    image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
    workingDir: $(workspaces.workdir.path)
    args:
    - use
    - $(params.source-artifact)=source
  
  - name: run-script
    image: $(params.script-environment-image)
    workingDir: $(workspaces.workdir.path)/source/$(params.context)
    script: |
      #!/usr/bin/env bash
      set -euxo pipefail
      echo "--- Running custom pre-build script ---"
      
      $(params.script-content)
      
      echo "--- Custom pre-build script finished successfully ---"
  
  - name: create-trusted-artifact
    image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
    workingDir: $(workspaces.workdir.path)
    args:
    - create
    - source=$(params.ociStorage):pre-build-$(context.taskRun.uid)
    - --expires-after=$(params.ociArtifactExpiresAfter)
    - --results-file=$(results.manipulated-source-artifact.path)
